# Simple workflow for deploying static content to GitHub Pages
# Adapted from vite.dev
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

env:
  AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_CELLS_ACCOUNT_ID }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Build with Vite
        run: bun run build --base=/cellpack-client

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          clean-exclude: pr-preview/
          branch: gh-pages

  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github_cellpack
          role-session-name: github_cellpack-${{ env.SHORT_SHA }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Build with Vite
        run: bun run build

      - name: Copy files to production bucket
        run: aws s3 sync ./dist/ s3://cellpack-datasets/ --delete
